config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
    controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  root to: 'pages#home'

  resources :farms, only: [:index, :show]
  resources :orders, only: [:create, :index, :update, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/farm.rb
class Farm < ApplicationRecord
  geocoded_by :address
  after_validation :geocode, if: :address_changed?
  belongs_to :user
  has_many :products
  validates :name, presence: true
  validates :address, presence: true
end

app/models/order.rb
class Order < ApplicationRecord
  after_create :send_new_order_email

  belongs_to :user
  belongs_to :product

  ORDER_RATING = [1, 2, 3, 4, 5]

  validates :quantity, presence: true
  validates :quantity, numericality: { greater_than: 0 }
  validates :rating, inclusion: { in: ORDER_RATING, on: :update }
  validates :review, length: { minimum: 30, on: :update }

  scope :pendings, -> { where('delivery_time > ?', Time.now) }
  scope :past, -> { where('delivery_time <= ?', Time.now) }
  
  def delivery_time_is_in_the_past?
    delivery_time < Date.today
  end

  # def rated?
  #   created_at != updated_at
  # end

  private

  def send_new_order_email
    UserMailer.new_order(self).deliver_now
  end
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :farm
  has_many :users, through: :orders

  validates :name, presence: true
  validates :price, numericality: { greater_than_or_equal_to: 0 }
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, omniauth_providers: [:facebook]
  has_many :farms
  has_many :products, through: :orders
  def self.find_for_facebook_oauth(auth)
    user_params = auth.slice(:provider, :uid)
    user_params.merge! auth.info.slice(:email, :first_name, :last_name)
    user_params[:facebook_picture_url] = auth.info.image
    user_params[:token] = auth.credentials.token
    user_params[:token_expiry] = Time.at(auth.credentials.expires_at)
    user_params = user_params.to_h

    user = User.find_by(provider: auth.provider, uid: auth.uid)
    user ||= User.find_by(email: auth.info.email) # User did a regular sign up in the past.
    if user
      user.update(user_params)
    else
      user = User.new(user_params)
      user.password = Devise.friendly_token[0,20]  # Fake password for validation
      user.save
    end

    return user
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  layout :layout

  def layout
    if devise_controller?
      'devise'
    else
      'application'
    end
  end
end

app/controllers/farms_controller.rb
class FarmsController < ApplicationController
  def index
    @farms = Farm.all
    @hash = Gmaps4rails.build_markers(@farms) do |farm, marker|
      marker.lat farm.latitude
      marker.lng farm.longitude
      marker.infowindow render_to_string(partial: '/components/map_box', locals: { farm: farm })
    end
  end

  def show
    @farm = Farm.find(params[:id])
    @products = Product.where(farm_id: @farm)
    @orders = Order.where(product_id: @products)
    @order = Order.new
    @farm_coordinates = { lat: @farm.latitude, lng: @farm.longitude }
    @hash = Gmaps4rails.build_markers(@farm) do |farm, marker|
      marker.lat farm.latitude
      marker.lng farm.longitude
    end
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :find_product, only: [:create]
  before_action :find_user, only: [:create]
  before_action :find_order, only: [:update, :destroy]

  def create
    @order = Order.new(order_params)
    @order.product = @product
    @order.user = @user

    @farm = @order.product.farm
    @products = Product.where(farm_id: @farm)
    @orders = Order.where(product_id: @products)
    if @order.delivery_time_is_in_the_past?
      render 'farms/show'
    elsif @order.save
      redirect_to orders_path
    else
      render 'farms/show'
    end
  end

  def index
    @orders = Order.where(user: current_user)
    @pending_orders = @orders.pendings
    @past_orders = @orders.past
  end

  def update
    if @order.update(review_params)
      redirect_to orders_path
    else
      @orders = Order.where(user: current_user)
      @pending_orders = @orders.pendings
      @past_orders = @orders.past
      @review = params[:order][:review]
      render :index
    end
  end

  def destroy
    @order.destroy

    respond_to do |format|
      format.html { redirect_to orders_path }
      format.js
    end
  end

  private

  def review_params
    params.require(:order).permit(:rating, :review)
  end

  def order_params
    params.require(:order).permit(:quantity, :delivery_time, :product_id)
  end

  def find_order
    @order = Order.find(params[:id])
  end

  def find_product
    @product = Product.find(params[:order][:product_id].to_i)
  end

  def find_user
    @user = current_user
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @farms = Farm.last(6)
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all
    render 'farms/show'
  end

end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    user = User.find_for_facebook_oauth(request.env['omniauth.auth'])

    if user.persisted?
      sign_in_and_redirect user, event: :authentication
      set_flash_message(:notice, :success, kind: 'Facebook') if is_navigational_format?
    else
      session['devise.facebook_data'] = request.env['omniauth.auth']
      redirect_to new_user_registration_url
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def yield_with_default(holder, default)
    if content_for?(holder)
      content_for(holder).squish
    else
      default
    end
  end
end

app/helpers/farms_helper.rb
module FarmsHelper
  # def check_photo(farm)
  #   if farm.photo.nil?
  #     "goo.gl/S2K83Y"
  #   else
  #     cl_image_path farm.photo.path
  #   end
  # end
end

app/views/farms/_farm_map.html.erb
<script>
  var handler = Gmaps.build('Google');
  handler.buildMap({ internal: { id: 'map' } }, function() {
    markers = handler.addMarkers(<%= raw @hash.to_json %>);
    handler.bounds.extendWith(markers);
    handler.fitMapToBounds();
    if (markers.length == 0) {
      handler.getMap().setZoom(2);
    } else if (markers.length == 1) {
      handler.getMap().setZoom(14);
    }
  });
</script>

app/views/farms/_farms_map.html.erb
<script>
const handler = Gmaps.build('Google');
handler.buildMap({ internal: { id: 'map' } }, function() {
  markers = handler.addMarkers(<%= raw @hash.to_json %>);
  handler.bounds.extendWith(markers);
  handler.fitMapToBounds();
  if (markers.length == 0) {
    handler.getMap().setZoom(2);
  } else if (markers.length == 1) {
    handler.getMap().setZoom(14);
  }
});

const getLocation = () => {
  if (navigator.geolocation) {
      navigator.geolocation.getCurrentPosition(showPosition);
  }
}

let latitude = '';
let longitude = '';

const showPosition = (position) => {
  latitude = position.coords.latitude;
  longitude = position.coords.longitude;

  const mapOptions = {
    center: new google.maps.LatLng(latitude, longitude),
    zoom: 12
  };

  const handler = Gmaps.build('Google');
  handler.buildMap({ provider: mapOptions, internal: { id: 'map' } }, function() {
    markers = handler.addMarkers(<%= raw @hash.to_json %>);
    handler.bounds.extendWith(markers);
    if (markers.length == 0) {
      handler.getMap().setZoom(2);
    } else if (markers.length == 1) {
      handler.getMap().setZoom(14);
    }
  });
}

getLocation();
</script>

app/views/farms/index.html.erb
<% content_for(:title) do%>
  <%= 'Farmland farms' %>
<% end %>

<div id="map" style="width: 100%; height: 600px;"></div>

<div class="container">
  <div class="farms">
    <h1>Find the best products around you!</h1>
    <div class="row">
      <% @farms.each do |farm| %>
        <div class="col-sm-4">
          <%= link_to farm_path(farm) do %>
            <div class="card-container" style="background-image: linear-gradient(rgba(40, 40, 40 ,0.4), rgba(40, 40, 40 ,0.7)), url('<%= farm.photo %>');">
              <div class="card">
                <h2><%= farm.name %></h2>
                <span><i class="fa fa-map-marker" aria-hidden="true"></i>  <%= farm.address %></span>
              </div>
            </div>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
</div>

<% content_for(:after_js) do %>
  <%= render 'farms_map' %>
<% end %>

app/views/farms/show.html.erb
<% content_for(:title) do%>
  <%= "Farmland - #{@farm.name}" %>
<% end %>
<input type="hidden" id="address" value="<%= @farm.address %>">

<div class="farm-banner" style="background-image: linear-gradient(rgba(0, 0, 0 ,0.4), rgba(0, 0, 0 ,0.3)), url('<%= image_path @farm.photo %>');">
  <h1><%= @farm.name %></h1>
</div>

<div class="container">
  <div class="products">
    <h2>Products</h2>
    <% @farm.products.each do |product| %>
      <div class="product">
        <h3><%= product.name.capitalize %></h3>
        <div class="row">
          <div class="col-sm-6">
            <div class="picture" style="background-image: url('<%= image_path product.photo %>');">
            </div>
          </div>
          <div class="col-sm-5 col-sm-offset-1">
            <p class="price">Unit price: <strong><%= product.price %>€</strong></p>
            <% if user_signed_in? %>
              <%= render 'orders/new_form', product: product %>
            <% else %>
              <div class="login-card">
                <p>Before adding a product to your cart, you have to create an account or to login:</p>
                <p><%= link_to 'Connect with facebook', user_facebook_omniauth_authorize_path, class: 'btn btn-primary' %></p>
                <div class="">
                  <%= link_to 'Login', new_user_session_path, class: 'btn btn-default' %>
                  <%= link_to 'Signup', new_user_registration_path, class: 'btn btn-default' %>
                </div>
              </div>
            <% end %>
          </div>
          <div class="col-sm-12">
            <p class="description"><%= product.description %></p>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

<div class="container">
  <div class="farm">
    <h2>About the farm</h2>
    <div class="row">
      <div class="col-sm-6">
        <div id="map" style="width: 100%; height: 600px;">
        </div>
      </div>

      <div class="col-sm-5 col-sm-offset-1">
        <div class="details">
          <h4><i class="fa fa-map-marker" aria-hidden="true"></i> Location</h3>
          <p><%= @farm.address %></p>
          <%= link_to 'Get directions', "https://www.google.com/maps/dir/?api=1&destination=#{@farm.address}", class: 'btn btn-lg btn-default', target: '_blank' %>
          <h4><i class="fa fa-envelope-o" aria-hidden="true"></i> Contact</h3>
          <p><%= @farm.user.first_name || @farm.user.email %></p>
          <%= link_to 'Contact owner', "mailto:#{@farm.user.email}", class: 'btn btn-lg btn-default' %>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="container">
  <div class="reviews">
    <h2>Last reviews</h2>
    <% @orders.each do |order| %>
      <div class="review">
        <p class="author"><%= order.user.first_name ? order.user.first_name : 'Anonymous' %></p>
        <div class="rating">
          <% order.rating.to_i.times do %>
            <i class="fa fa-star star-active" aria-hidden="true"></i>
          <% end %>
          <% (5 - order.rating.to_i).times do %>
            <i class="fa fa-star-o" aria-hidden="true"></i>
          <% end %>
        </div>
        <span class="date"><%= order.updated_at.strftime('%D') %></span>
        <p><%= order.review %></p>
      </div>
    <% end %>
  </div>
</div>

<input type="hidden" id="address" value="<%= @farm.address %>">

<% content_for(:after_js) do %>
  <script>
    const coord = <%= raw @farm_coordinates.to_json %>;
  </script>
<% end %>

<% content_for(:after_js) do %>
  <%= render 'farms/farm_map' %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title><%= yield_with_default(:title, "Farmland") %></title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
  </head>
  <body>
    <%= render "components/navbar" %>
    <%= render "components/flashes" %>
    <%= yield %>
    <%= render "components/footer" %>
    <%= javascript_include_tag "https://maps.google.com/maps/api/js?libraries=places&key=#{ENV['GOOGLE_API_KEY']}" %>
    <%= javascript_include_tag "https://cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/markerclusterer/src/markerclusterer_compiled.js" %>
    <%= javascript_include_tag "https://cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js" %>

    <%= javascript_include_tag "application" %>

    <%= yield(:after_js) %>
  </body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Farmland</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
  </head>
  <body>
    <%= render "components/navbar" %>
    <%= render "components/flashes" %>
    <div class="devise-wrapper">
      <div class="devise-container">
        <%= yield %>
      </div>
    </div>

    <%= javascript_include_tag "application" %>
    <%= yield(:after_js) %>
  </body>
</html>

app/views/orders/_edit_form.html.erb
<div class="form-review collapse" id="<%="collapse-#{order.id}"%>">
  <%= simple_form_for(order) do |f| %>
    <div class="col-sm-4">
      <%= f.input :rating, collection: Order::ORDER_RATING %>
    </div>
    <div class="col-sm-12">
      <%= f.hidden_field :updated_at %>
      <% if params[:id] && order.id == params[:id].to_i %>
        <%= f.input :review, input_html: {value: @review} %>
      <% else %>
        <%= f.input :review %>
      <% end %>
    </div>
    <div class="col-sm-12">
      <%= f.submit class: 'btn btn-lg btn-primary', value: 'Publish' %>
    </div>
  <% end %>
</div>

app/views/orders/_new_form.html.erb
<div class="form">
  <%= simple_form_for @order do |f| %>
  <%= f.hidden_field :product_id, value: product.id %>
  <%= f.input :quantity %>
  <%= f.input :delivery_time %>
  <%= f.submit class: 'btn btn-lg btn-primary', submit_html: { value: 'toto' } %>
  <% end %>
</div>

app/views/orders/destroy.js.erb
const order = document.querySelector('#order-<%= @order.id %>');
order.remove();

app/views/orders/index.html.erb
<div class="container">
  <div class="orders">
    <h1>My orders</h1>
    <div class="row">
      <h2>Pending orders</h2>
      <% @pending_orders.each do |order| %>
        <div id="order-<%= order.id %>" class="order panel panel-success">
          <div class="panel-heading">
            <h3 class="panel-title"><%= order.product.name %><span><%= order.created_at.strftime('%D') %></span></h3>
          </div>
          <div class="panel-body">
            <div class="row">
              <div class="col-sm-4">
                <%= link_to farm_path(order.product.farm) do %>
                  <div class="order-image" style="background-image: url('<%= order.product.photo %>');"></div>
                <% end %>
              </div>
              <div class="col-sm-8">
                <ul class="list-group">
                  <li class="list-group-item">Total price: <span class="pull-right"><%= order.quantity * order.product.price %>€</span></li>
                  <li class="list-group-item">Order date: <span class="pull-right"><%= order.delivery_time.strftime('%D') %></span></li>
                  <li class="list-group-item">Quantity:<span class="pull-right"><%= order.quantity %></span></li>
                </ul>
                <div class="col-sm-4 col-sm-offset-4">
                  <%= link_to "Cancel order", order_path(order), method: :delete, remote: true, class: 'btn btn-danger', data: { confirm: "Are you sure you want to cancel this order?" } %>
                </div>
              </div>
            </div>
          </div>
        </div>
      <% end %>

      <h2>Past orders</h2>
      <% @past_orders.each do |order| %>
        <div id="order-<%= order.id %>" class="order panel panel-success">
          <div class="panel-heading">
            <h3 class="panel-title"><%= order.product.name %><span><%= order.created_at.strftime('%D') %></span></h3>
          </div>
          <div class="panel-body">
            <div class="row">
              <div class="col-sm-4">
                <%= link_to farm_path(order.product.farm) do %>
                  <div class="order-image" style="background-image: url('<%= order.product.photo %>');"></div>
                <% end %>
              </div>
              <div class="col-sm-8">
                <ul class="list-group">
                  <li class="list-group-item">Total price: <span class="pull-right"><%= order.quantity * order.product.price %>€</span></li>
                  <li class="list-group-item">Order date: <span class="pull-right"><%= order.delivery_time.strftime('%D') %></span></li>
                  <li class="list-group-item">Quantity:<span class="pull-right"><%= order.quantity %></span></li>
                </ul>
                <div class="col-sm-4 col-sm-offset-4">
                  <%= link_to 'Review', "#collapse-#{order.id}", 'aria-expanded': 'false', 'aria-controls': 'collapseExample', 'data-toggle': 'collapse', role: 'button', class: 'btn btn-primary button-review' %>
                </div>
              </div>
              <div class="col-sm-12">
                <%= render 'edit_form', order: order %>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/pages/home.html.erb
<% content_for(:title) do%>
  <%= 'Welcome' %>
<% end %>

<div class="banner" style="background-image: linear-gradient(rgba(40, 40, 40 ,0.4), rgba(40, 40, 40 ,0.7)), url('<%= image_path 'banner-bg.jpg' %>');">
  <div class="banner-content">
    <h1>Farmland</h1>
    <p class="description">Localize farms around you for healthy food delivered.</p>
    <%= link_to 'Browse farms' , farms_path, class: 'btn btn-lg btn-primary' %>
  </div>
</div>

<div class="container">
  <div class="last-farms">
    <h2>Last farms</h2>
    <div class="row">
      <% @farms.each do |farm| %>
        <div class="col-sm-4">
          <%= link_to farm_path(farm) do %>
            <div class="card-container" style="background-image: linear-gradient(rgba(40, 40, 40 ,0.4), rgba(40, 40, 40 ,0.7)), url('<%= farm.photo %>');">
              <div class="card">
                <h2><%= farm.name %></h2>
                <span><i class="fa fa-map-marker" aria-hidden="true"></i>  <%= farm.address %></span>
              </div>
            </div>
          <% end %>
        </div>
      <% end %>
    </div>
    <div class="all-farm-link">
      <%= link_to 'Browse all farms', farms_path, class: 'btn btn-lg btn-primary'%>
    </div>
  </div>
</div>